apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastic
  name: elasticsearch-es-http
  namespace: elastic
spec:
  type: NodePort
  ports:
    - name: internal
      port: 9200
      protocol: TCP
      targetPort: 9200
