apiVersion: v1 
kind: PersistentVolume 
metadata:
  name : datadir 
spec: 
  capacity:
    storage: 3Gi
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path : /home/zookeper

---

apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: datadir-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 2Gi
