apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: elastic
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: elastic
  labels:
    app: zookeeper
spec:
  type: NodePort
  ports:
    - name: zk-client
      port: 2181
      targetPort: 2181
      nodePort: 30003
  selector:
    app: zookeeper