kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  namespace: elastic
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
    nodePort: 30008
  type: NodePort
