apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
spec:
  type: NodePort
  ports:
    - name: internal
      port: 9092
      protocol: TCP
      targetPort: 9092
      nodePort: 30006

    - name: external
      port: 9094
      protocol: TCP
      targetPort: 9094
      nodePort: 30007
  selector:
    app: kafka